### ISSUE TITLE
Reporte de Práctica

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/practica-de-visual-studio-Yabin-2021#2]
[Reporte de Práctica - GUI1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Yabin-2021/files/6165033/Reporte.de.Practica.-.GUI1.pdf)

**Comment by IsaHuerta23** [comment]
Observaciones:
-El índice no debe ir en la misma hoja que el contenido. 
-El índice no debe estar numerado.
-El contenido debe empezar en la página 1 y no en la 2.
-Algunas ilustraciones no están centradas.


[Rubrica 2 Practica 2 (EVALUADA).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Yabin-2021/files/6172144/Rubrica.2.Practica.2.EVALUADA.pdf)

**Comment by IsaHuerta23** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
